// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNt9wAnEuI1O286uYqrjUh2UNcSAhoXuU',
    appId: '1:513336558280:web:2f5734d8c9293600a4dbfd',
    messagingSenderId: '513336558280',
    projectId: 'spotifind-id',
    authDomain: 'spotifind-id.firebaseapp.com',
    storageBucket: 'spotifind-id.firebasestorage.app',
    measurementId: 'G-Z5Y3T8E56N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCunbI6xkH5f-XOpCYjyjuCk5Kif7L_mQI',
    appId: '1:513336558280:android:c231b665489b67f0a4dbfd',
    messagingSenderId: '513336558280',
    projectId: 'spotifind-id',
    storageBucket: 'spotifind-id.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_3L1zdde1bkuQ6ZoN-1txJR4u6VbQG7w',
    appId: '1:513336558280:ios:0669407c072c8d16a4dbfd',
    messagingSenderId: '513336558280',
    projectId: 'spotifind-id',
    storageBucket: 'spotifind-id.firebasestorage.app',
    iosClientId: '513336558280-urbr16rqkt03ddiib2ccjlibpp7id7de.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_3L1zdde1bkuQ6ZoN-1txJR4u6VbQG7w',
    appId: '1:513336558280:ios:0669407c072c8d16a4dbfd',
    messagingSenderId: '513336558280',
    projectId: 'spotifind-id',
    storageBucket: 'spotifind-id.firebasestorage.app',
    iosClientId: '513336558280-urbr16rqkt03ddiib2ccjlibpp7id7de.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNt9wAnEuI1O286uYqrjUh2UNcSAhoXuU',
    appId: '1:513336558280:web:f9a2c099d6578149a4dbfd',
    messagingSenderId: '513336558280',
    projectId: 'spotifind-id',
    authDomain: 'spotifind-id.firebaseapp.com',
    storageBucket: 'spotifind-id.firebasestorage.app',
    measurementId: 'G-GNFNF0Z5TQ',
  );
}
